class_name HotelLocalization
extends RefCounted

const AnomalyCollectionContent := preload("res://scripts/horror/anomaly_collection_content.gd")
const SceneLocalizationContent := preload("res://scripts/scenes/hotel_scene_localization.gd")

signal language_changed(language: int)

enum Language {
	ENGLISH,
	KOREAN,
	JAPANESE,
	RUSSIAN,
	CHINESE,
}

const DEFAULT_LANGUAGE := Language.KOREAN
const FALLBACK_LANGUAGE := Language.ENGLISH
const SUPPORTED_LANGUAGES := [
	Language.ENGLISH,
	Language.KOREAN,
	Language.JAPANESE,
	Language.RUSSIAN,
	Language.CHINESE,
]
const LANGUAGE_CODES := {
	Language.ENGLISH: "en",
	Language.KOREAN: "ko",
	Language.JAPANESE: "ja",
	Language.RUSSIAN: "ru",
	Language.CHINESE: "zh",
}

var current_language := DEFAULT_LANGUAGE
var translations := {
	Language.ENGLISH: {
		"ui.menu.title": "Menu",
		"ui.menu.continue": "Continue",
		"ui.menu.inventory": "Inventory",
		"ui.menu.rule_book": "Rule Book",
		"ui.menu.controls": "Controls",
		"ui.controls.title": "Controls",
		"ui.controls.close_eyes": "Close or open your eyes",
		"ui.controls.use_item": "Use the item equipped in Hand",
		"ui.controls.mouse": "Mouse",
		"ui.controls.interact": "Aim at and interact with objects",
		"ui.controls.drag": "Inventory",
		"ui.controls.equip": "Drag, double-click, or right-click to equip",
		"ui.controls.pause": "Open or close this menu",
		"ui.controls.eye_hint": "With your eyes closed, only the area beneath the cursor remains visible.",
		"ui.debug.eyes.radius": "Closed-eye vision radius",
		"ui.debug.eyes.height": "Closed-eye opening height",
		"ui.debug.tabs.general": "General",
		"ui.debug.tabs.scene": "Scene",
		"ui.debug.tabs.anomaly": "Anomaly",
		"ui.debug.tabs.vision": "Vision",
		"ui.debug.tabs.presentation": "Presentation",
		"ui.debug.console.show": "Show debug console",
		"ui.debug.console.hide": "Hide debug console",
		"ui.debug.filters.show": "Show filter selector",
		"ui.debug.filters.hide": "Hide filter selector",
		"ui.debug.filters.title": "Filter",
		"ui.debug.filters.tooltip": "Apply this screen filter.",
		"ui.debug.filters.intensity": "Intensity",
		"ui.debug.filters.intensity_tooltip": "Filter intensity.",
		"ui.debug.filters.preset.none": "No filter",
		"ui.debug.filters.preset.dreary_1": "Dreary 1",
		"ui.debug.filters.preset.subtle_grain": "CRT static",
		"ui.debug.curtain.tooltip.available": "Compare the bathroom photo in gameplay, open, and closed states.",
		"ui.debug.curtain.tooltip.unavailable": "Enter a Room 105–108 bathroom to compare curtain photos.",
		"ui.debug.curtain.mode.gameplay": "Gameplay",
		"ui.debug.curtain.mode.open": "Open",
		"ui.debug.curtain.mode.closed_edit": "Closed A · edit_002",
		"ui.debug.anomaly.tooltip": "Force one confirmed anomaly. Events without a completed resolution are previews only.",
		"ui.debug.anomaly.preview": "Anomaly preview",
		"ui.debug.jumpscare_lab.title": "Jumpscare Lab",
		"ui.debug.jumpscare_lab.tooltip": "Adjust source scale, lunge timing and speed, and screen shake, then preview the result.",
		"ui.debug.jumpscare_lab.close": "Close",
		"ui.debug.jumpscare_lab.intro": "Adjust the values and preview the result. Changes are used only in this lab and are not saved to game data.",
		"ui.debug.jumpscare_lab.entity": "Entity",
		"ui.debug.jumpscare_lab.source_fit": "Source fit",
		"ui.debug.jumpscare_lab.fit.cover": "Fill screen · Cover",
		"ui.debug.jumpscare_lab.fit.contain": "Original ratio · Contain",
		"ui.debug.jumpscare_lab.preview": "Preview current values",
		"ui.debug.jumpscare_lab.reset": "Entity defaults",
		"ui.debug.jumpscare_lab.status.safe": "Previews do not change death state or saves.",
		"ui.debug.jumpscare_lab.status.playing": "%s preview playing · deaths/saves unaffected",
		"ui.debug.jumpscare_lab.status.loaded": "%s defaults loaded",
		"ui.debug.jumpscare_lab.suffix.seconds": " s",
		"ui.debug.jumpscare_lab.suffix.times": "×",
		"ui.debug.jumpscare_lab.suffix.pixels": " px",
		"ui.debug.jumpscare_lab.suffix.decibels": " dB",
		"ui.debug.jumpscare_lab.field.jumpscare_hold_seconds.label": "Lunge delay",
		"ui.debug.jumpscare_lab.field.jumpscare_hold_seconds.hint": "Time from first appearance until the lunge starts",
		"ui.debug.jumpscare_lab.field.jumpscare_initial_zoom.label": "Initial scale",
		"ui.debug.jumpscare_lab.field.jumpscare_initial_zoom.hint": "Size of the source image when it first appears",
		"ui.debug.jumpscare_lab.field.jumpscare_lunge_seconds.label": "Lunge duration",
		"ui.debug.jumpscare_lab.field.jumpscare_lunge_seconds.hint": "Time required to reach the final scale",
		"ui.debug.jumpscare_lab.field.jumpscare_lunge_zoom.label": "Lunge scale",
		"ui.debug.jumpscare_lab.field.jumpscare_lunge_zoom.hint": "Scale at the end of the lunge",
		"ui.debug.jumpscare_lab.field.jumpscare_duration.label": "Total duration",
		"ui.debug.jumpscare_lab.field.jumpscare_duration.hint": "Time from first appearance until the preview ends",
		"ui.debug.jumpscare_lab.field.jumpscare_focus_x.label": "Focus X",
		"ui.debug.jumpscare_lab.field.jumpscare_focus_x.hint": "0 is left; 1 is right",
		"ui.debug.jumpscare_lab.field.jumpscare_focus_y.label": "Focus Y",
		"ui.debug.jumpscare_lab.field.jumpscare_focus_y.hint": "0 is top; 1 is bottom",
		"ui.debug.jumpscare_lab.field.jumpscare_initial_shake.label": "Initial shake",
		"ui.debug.jumpscare_lab.field.jumpscare_initial_shake.hint": "Screen shake on the first frame",
		"ui.debug.jumpscare_lab.field.jumpscare_lunge_shake.label": "Lunge shake",
		"ui.debug.jumpscare_lab.field.jumpscare_lunge_shake.hint": "Screen shake at the lunge",
		"ui.debug.jumpscare_lab.field.jumpscare_audio_volume_db.label": "Impact volume",
		"ui.debug.jumpscare_lab.field.jumpscare_audio_volume_db.hint": "Preview volume",
		"ui.debug.anomaly_transition.preview": "Fade preview",
		"ui.debug.anomaly_transition.preview_tooltip": "Preview the anomaly disappearance transition without changing game state.",
		"ui.debug.anomaly_transition.duration": "Anomaly fade duration",
		"ui.debug.anomaly_transition.value": "Black %.2fs / total %.2fs",
		"ui.menu.brightness": "Brightness",
		"ui.menu.main_menu": "Main Menu",
		"ui.menu.quit": "Quit",
		"ui.shift.end": "End Shift",
		"ui.day.label": "Day %d",
		"ui.infinity.day.label": "Night %d",
		"ui.lobby.title": "Night Shift",
		"ui.lobby.subtitle": "The front desk is waiting.",
		"ui.lobby.start_shift": "Start Shift",
		"ui.lobby.mode.story": "Story",
		"ui.lobby.mode.infinity": "Infinity",
		"ui.lobby.mode.story.description": "A seven-night story with a fixed authored anomaly schedule.",
		"ui.lobby.mode.infinity.description": "An endless shift with random reusable anomalies and no fixed story order.",
		"ui.lobby.start_story": "Start Story",
		"ui.lobby.start_infinity": "Start Infinity",
		"ui.lobby.continue_story": "Continue Story",
		"ui.lobby.continue_infinity": "Continue Infinity",
		"ui.lobby.choose_infinity_night": "Choose Saved Night",
		"ui.intro.dialogue.1": "At 12:47 a.m., an unfamiliar number called.\n‘Unclaimed wages remain under your name. Come collect them in person.’",
		"ui.intro.dialogue.2": "I had never worked at this hotel.\nBut the employee record carried my name and two phone numbers.",
		"ui.intro.dialogue.3": "The second number was mine.",
		"ui.intro.dialogue.4": "I had been hiding from gambling debt and illegal work for a long time.\nMoney left under my name was difficult to ignore.",
		"ui.intro.dialogue.5": "The employee photograph showed my missing older sister.\nShe had worked here under my name while investigating rumors of disappearances and abductions.",
		"ui.intro.dialogue.6": "On the back of the record, she had written one line.\n‘Do not say you came looking for your younger sister.’",
		"ui.intro.dialogue.7": "But I am her younger sister.",
		"story.day.1.line.1": "At 12:47 a.m., an unfamiliar number called.\n‘Unclaimed wages remain under your name. Come collect them in person.’",
		"story.day.1.line.2": "I had never worked at this hotel. But after months spent hiding from gambling debt and illegal work, money left under my name was difficult to ignore.",
		"story.day.2.line.1": "A previous employee record was filed under my name. Two contact numbers had been written beneath it.",
		"story.day.3.line.1": "The second contact number was mine. It was the number I had changed after going into hiding.",
		"story.day.4.line.1": "The photograph attached to the record was my missing older sister. She had worked here under my name.",
		"story.day.5.line.1": "Dates and room numbers filled the margins of her record. She had been tracing rumors of people disappearing from this hotel.",
		"story.day.6.line.1": "One sentence remained on the back, in my sister’s handwriting.\n‘Do not say you came looking for your younger sister.’",
		"story.day.7.line.1": "She came here looking for her younger sister.\nI am that sister.",
		"night.phone.room_108_repair_call": "Room 108. The light is out. Come repair it. The line goes dead.",
		"night.child.hold_f_to_sing": "Hold F to sing.",
		"ui.lobby.continue": "Continue",
		"ui.lobby.continue.available": "Choose a saved day to continue.",
		"ui.lobby.continue.disabled": "No saved days yet.",
		"ui.lobby.choose_day": "Choose Day",
		"ui.lobby.save_status": "Latest saved day: %s",
		"ui.lobby.no_save_status": "No saved shift yet.",
		"ui.lobby.day.saved": "Start from this saved day.",
		"ui.lobby.day.locked": "Reach this day first.",
		"ui.lobby.horror_summary": "%s",
		"ui.lobby.horror_summary.none": "Anomalies found: 0",
		"ui.lobby.horror_summary.count": "Anomalies found: %d (%s)",
		"ui.anomaly_collection.kind.visual_anomaly": "Visual",
		"ui.anomaly_collection.kind.jumpscare": "Jumpscare",
		"ui.lobby.anomaly_collection": "Anomaly Collection",
		"ui.lobby.quit": "Quit",
		"ui.anomaly_collection.title": "Anomaly Collection",
		"ui.anomaly_collection.count": "Discovered: %d · Entities: %d · Phenomena: %d",
		"ui.anomaly_collection.empty": "No anomalies discovered yet.",
		"ui.anomaly_collection.kind.entity": "Entity",
		"ui.anomaly_collection.kind.phenomenon": "Phenomenon",
		"ui.anomaly_collection.body.story": "STORY",
		"ui.anomaly_collection.body.description": "PHENOMENON DESCRIPTION",
		"ui.anomaly_collection.type.anomaly": "Anomaly",
		"ui.anomaly_collection.type.jumpscare": "Jumpscare",
		"ui.anomaly_collection.status.active": "Observed",
		"ui.anomaly_collection.status.resolved": "Resolved",
		"ui.inventory.title": "Inventory",
		"ui.inventory.hint": "Equip by dragging, double-clicking, or right-clicking. Drop one item onto another to combine them.",
		"ui.inventory.empty": "No items yet.",
		"ui.inventory.combine.no_match": "Those items do not fit together.",
		"ui.inventory.hand.title": "Hand",
		"ui.inventory.hand.empty": "Nothing equipped",
		"ui.inventory.hand.empty_hint": "Drop or select an item",
		"ui.inventory.hand.status.empty": "○ EMPTY",
		"ui.inventory.hand.status.equipped": "● EQUIPPED",
		"ui.inventory.hand.use_hint": "Press F to use",
		"ui.equipment.empty": "Empty",
		"ui.equipment.tooltip": "Open inventory",
		"ui.rule_book.title": "Hotel Management Rules",
		"ui.rule_book.subtitle": "Issued by: Manager",
		"ui.rule_book.day": "DAY %d · NEW RULES",
		"ui.rule_book.latest": "LATEST",
		"ui.rule_book.previous_day": "Previous day",
		"ui.rule_book.next_day": "Next day",
		"ui.rule_book.rule.1": "Make the beds in every vacant room.",
		"ui.rule_book.rule.2": "Put all trash found in a room in its trash can.",
		"ui.rule_book.rule.3": "Every other day, place used bedding in the laundry hamper.",
		"ui.rule_book.rule.4": "If a guest-room wardrobe door is open, close it.",
		"ui.rule_book.rule.5": "If Room 108 calls to request a light repair, ignore the request. Do not enter the room.",
		"ui.rule_book.rule.6": "Beginning on the third day, if the door to Room 109 is open, do not look inside.",
		"ui.rule_book.rule.7": "Answer the front desk phone before the thirteenth ring.",
		"ui.rule_book.rule.8": "If you see something strange inside a washer, stop the wash. While the completion song plays, close your eyes and hide in the laundry room.",
		"ui.rule_book.rule.12": "If you find a crying child, close your eyes and sing.",
		"ui.rule_book.rule.14": "Tonight, leave the door to Room 109 open.",
		"ui.rule_book.rule.15": "Do not stop whoever comes out of Room 109.",
		"ui.rule_book.rule.16": "Do not turn around until the footsteps have stopped.",
		"ui.rule_book.rule.17": "Give a doll to a cute girl.",
		"ui.rule_book.rule.18": "If someone is following you, ring the bell several times quickly and run.",
		"ui.debug.hotspots.show": "Show click areas",
		"ui.debug.hotspots.hide": "Hide click areas",
		"ui.debug.dialogue.show": "Show dialogue panel",
		"ui.debug.dialogue.hide": "Hide dialogue panel",
		"ui.debug.navigation.show": "Show quick travel buttons",
		"ui.debug.navigation.hide": "Hide quick travel buttons",
		"ui.debug.days.title": "Day",
		"ui.debug.days.tooltip": "Jump to this day and autosave the current day.",
		"item.room_105_key.name": "Room 105 Key",
		"item.room_105_key.description": "A worn brass key from the front desk drawer.",
		"item.small_flashlight.name": "Flashlight",
		"item.small_flashlight.description": "A compact flashlight. Useful when the power fails.",
		"item.guest_note.name": "Guest Note",
		"item.guest_note.description": "A folded note with a room number written in pencil.",
		"item.revealed_guest_note.name": "Revealed Note",
		"item.revealed_guest_note.description": "The flashlight reveals faint writing under the room number: Do not return it after midnight.",
		"item.cleaning_cloth.name": "Cleaning Cloth",
		"item.cleaning_cloth.description": "A rough cloth for wiping sinks, floors, and anything that should not be touched directly.",
		"item.small_mirror.name": "Small Mirror",
		"item.small_mirror.description": "A small hand mirror. Its surface is unusually clear.",
		"item.hell_mirror.name": "Mirror of Hell",
		"item.hell_mirror.description": "The trapped screaming swells while it is held. A washer drum may be the only place deep enough to break it.",
		"horror.room_106_horrific_mirror.transferred": "The horrific image moved into the small mirror. You can hear souls screaming while you hold it.",
		"item.cute_doll.name": "Cute Doll",
		"item.cute_doll.description": "A small wooden doll found on the laundry-room table. It can be held, but only needs to be in your inventory to offer it.",
		"item.collected_trash.name": "Collected Trash",
		"item.collected_trash.description": "Loose papers and trash gathered during room work.",
		"combine.reveal_guest_note": "The flashlight reveals hidden writing on the note.",
		"task.room_105_fold_bedding.label": "Bedding",
		"task.room_105_fold_bedding.text": "The bed is not quite ready for a guest.",
		"task.room_105_fold_bedding.done": "You fold the bedding into a neat, stiff square.",
		"task.room_105_clean_sink.label": "Sink Stain",
		"task.room_105_clean_sink.text": "The sink has a dull stain that should be wiped down.",
		"task.room_105_clean_sink.done": "The sink looks clean enough for the next guest.",
		"task.room_105_clean_sink.blocked": "You need something to wipe the sink with.",
		"task.room_107_collect_papers.label": "Loose Papers",
		"task.room_107_collect_papers.text": "A few papers are scattered on the carpet.",
		"task.room_107_collect_papers.done": "You collect the loose papers from the carpet.",
		"hotspot.laundry_room.laundry_second_washer.opened": "The second washer door is open.",
		"hotspot.laundry_room.laundry_second_washer.closed": "The second washer door is closed.",
		"horror.room.front_desk": "Front Desk",
		"horror.room.corridor": "Corridor",
		"horror.room.laundry_room": "Laundry Room",
		"horror.room.exterior_stairs": "Exterior Stairs",
		"horror.room.room_105": "Room 105",
		"horror.room.room_106": "Room 106",
		"horror.room.room_107": "Room 107",
		"horror.room.room_108": "Room 108",
		"horror.room.room_109": "Room 109",
		"hotspot.room_105_bathroom_entry.closet_pig_hold:wardrobe.label": "Close wardrobe",
		"hotspot.room_105_bathroom_entry.closet_pig_hold:wardrobe.text": "Hold to push him inside and close the wardrobe.",
		"horror_event.room_105_closet_pig_man.title": "Closet Pig-Mask Man",
		"horror_event.room_105_closet_pig_man.description": "A man in a pale pig mask forces his way out through the open wardrobe.",
		"horror_event.room_106_abandoned_child.title": "Abandoned Child",
		"horror_event.room_106_abandoned_child.description": "The crying stops directly behind you.",
		"horror_event.room_108_light_repair_call.title": "Thirteenth Ring",
		"horror_event.room_108_light_repair_call.description": "Room 108 calls once more. This time the voice is beside you.",
		"horror_event.room_109_open_door.title": "Room 109",
		"horror_event.room_109_open_door.description": "Something inside notices you looking.",
		"horror_event.room_109_day7_passage.title": "Room 109 Passage",
		"horror_event.room_109_day7_passage.description": "You turned before the footsteps behind you had stopped.",
		"horror_event.laundry_red_washer.title": "Red Laundry",
		"horror_event.laundry_red_washer.description": "The wet bundle moves as you look inside.",
		"horror_event.room_107_hanging_girl.title": "Hanged Wooden Girl Doll",
		"horror_event.room_107_hanging_girl.description": "The dangle-dangle game did not end when the body should have died.",
		"horror_event.vacant_room_blanket_child.title": "Child Under the Blanket",
		"horror_event.vacant_room_blanket_child.description": "A voice beneath the blanket whispers that it found you.",
		"horror_event.hotel_following_shadow.title": "Following Shadow",
		"horror_event.hotel_following_shadow.description": "The presence matching every footstep finally closes the distance behind you.",
		"horror_event.hell_mirror.title": "Mirror of Hell",
		"horror_event.hell_mirror.description": "The screaming trapped inside the mirror reaches the other side.",
		"horror.hanging_girl.prompt.interact": "A hanged wooden girl is looking this way.",
		"horror.hanging_girl.prompt.play": "Let's play dangle-dangle~ It'll be fun, right?",
		"horror.hanging_girl.prompt.angry": "You fucking bastard.",
		"horror.hanging_girl.prompt.which_game": "What game?",
		"horror.hanging_girl.prompt.who_walter": "Who's Walter?",
		"horror.hanging_girl.choice.talk": "Talk",
		"horror.hanging_girl.choice.ignore": "Ignore",
		"horror.hanging_girl.choice.fun_yes": "Looks fun",
		"horror.hanging_girl.choice.fun_no": "Doesn't look fun",
		"horror.hanging_girl.choice.changed_mind": "On second thought, it looks fun",
		"horror.hanging_girl.choice.you_play": "You go ahead",
		"horror.hanging_girl.choice.better_game": "I'll tell you a more fun game",
		"horror.hanging_girl.choice.doll_play": "Doll play",
		"horror.hanging_girl.choice.hide_and_seek": "Hide-and-seek",
		"horror.hanging_girl.choice.your_mom": "Your mom",
		"horror.hanging_girl.choice.walter": "Walter thinks it looks fun",
		"horror.hanging_girl.choice.doll_friend": "He's my doll friend",
		"horror.hanging_girl.death.1": "The rope tightened around the neck.",
		"horror.hanging_girl.death.2": "The body swung for a long time, unable to die.",
		"horror.hanging_girl.death.3": "The tongue pushed out of the mouth.",
		"horror.hanging_girl.death.4": "Vomit ran down the chin and chest.",
		"horror.hanging_girl.death.5": "The bowels released everything that remained inside.",
		"horror.hanging_girl.death.6": "The struggling stopped much later.",
	},
	Language.KOREAN: {
		"ui.menu.title": "메뉴",
		"ui.menu.continue": "계속하기",
		"ui.menu.inventory": "인벤토리",
		"ui.menu.rule_book": "룰 북",
		"ui.menu.controls": "조작법",
		"ui.controls.title": "단축키",
		"ui.controls.close_eyes": "눈 감기 / 눈 뜨기",
		"ui.controls.use_item": "Hand에 장착한 아이템 사용",
		"ui.controls.mouse": "마우스",
		"ui.controls.interact": "대상을 가리키고 상호작용",
		"ui.controls.drag": "인벤토리",
		"ui.controls.equip": "드래그·왼쪽 더블클릭·오른쪽 클릭으로 장착",
		"ui.controls.pause": "메뉴 열기 / 닫기",
		"ui.controls.eye_hint": "눈을 감으면 마우스 커서가 닿는 좁은 범위만 보입니다.",
		"ui.debug.eyes.radius": "눈 감기 시야 범위",
		"ui.debug.eyes.height": "눈 감기 시야 높이",
		"ui.debug.tabs.general": "기본",
		"ui.debug.tabs.scene": "장면",
		"ui.debug.tabs.anomaly": "기현상",
		"ui.debug.tabs.vision": "시야",
		"ui.debug.tabs.presentation": "연출",
		"ui.debug.console.show": "디버그 콘솔 표시",
		"ui.debug.console.hide": "디버그 콘솔 숨기기",
		"ui.debug.filters.show": "필터 선택 표시",
		"ui.debug.filters.hide": "필터 선택 숨기기",
		"ui.debug.filters.title": "필터",
		"ui.debug.filters.tooltip": "화면 필터를 적용합니다.",
		"ui.debug.filters.intensity": "강도",
		"ui.debug.filters.intensity_tooltip": "필터 강도를 조절합니다.",
		"ui.debug.filters.preset.none": "필터 없음",
		"ui.debug.filters.preset.dreary_1": "우중충한 필터 1",
		"ui.debug.filters.preset.subtle_grain": "브라운관 지지직",
		"ui.debug.curtain.tooltip.available": "욕실 사진을 게임 상태, 열린 상태, 닫힌 상태로 비교합니다.",
		"ui.debug.curtain.tooltip.unavailable": "105–108호 욕실에 들어가면 커튼 사진을 비교할 수 있습니다.",
		"ui.debug.curtain.mode.gameplay": "게임 상태",
		"ui.debug.curtain.mode.open": "열림",
		"ui.debug.curtain.mode.closed_edit": "닫힘 A · edit_002",
		"ui.debug.anomaly.tooltip": "확정된 기현상 하나를 강제로 실행합니다. 해결법이 완성되지 않은 이벤트는 프리뷰만 제공합니다.",
		"ui.debug.anomaly.preview": "기현상 프리뷰",
		"ui.debug.jumpscare_lab.title": "점프스케어 연구소",
		"ui.debug.jumpscare_lab.tooltip": "원본 확대, 돌진 시점과 속도, 화면 진동을 조절하고 프리뷰합니다.",
		"ui.debug.jumpscare_lab.close": "닫기",
		"ui.debug.jumpscare_lab.intro": "값을 조절한 뒤 프리뷰를 누르세요. 변경값은 연구소에서만 사용되며 게임 데이터에는 저장되지 않습니다.",
		"ui.debug.jumpscare_lab.entity": "엔티티",
		"ui.debug.jumpscare_lab.source_fit": "원본 맞춤",
		"ui.debug.jumpscare_lab.fit.cover": "화면 채우기 · Cover",
		"ui.debug.jumpscare_lab.fit.contain": "원본 비율 · Contain",
		"ui.debug.jumpscare_lab.preview": "현재 값으로 프리뷰",
		"ui.debug.jumpscare_lab.reset": "엔티티 기본값",
		"ui.debug.jumpscare_lab.status.safe": "프리뷰는 사망 판정과 저장을 변경하지 않습니다.",
		"ui.debug.jumpscare_lab.status.playing": "%s 프리뷰 재생 · 사망/저장 미적용",
		"ui.debug.jumpscare_lab.status.loaded": "%s 기본값 불러옴",
		"ui.debug.jumpscare_lab.suffix.seconds": " 초",
		"ui.debug.jumpscare_lab.suffix.times": " 배",
		"ui.debug.jumpscare_lab.suffix.pixels": " px",
		"ui.debug.jumpscare_lab.suffix.decibels": " dB",
		"ui.debug.jumpscare_lab.field.jumpscare_hold_seconds.label": "돌진 시작",
		"ui.debug.jumpscare_lab.field.jumpscare_hold_seconds.hint": "첫 등장 후 돌진을 시작할 때까지",
		"ui.debug.jumpscare_lab.field.jumpscare_initial_zoom.label": "원본 확대",
		"ui.debug.jumpscare_lab.field.jumpscare_initial_zoom.hint": "처음 나타나는 원본 사진의 크기",
		"ui.debug.jumpscare_lab.field.jumpscare_lunge_seconds.label": "돌진 시간",
		"ui.debug.jumpscare_lab.field.jumpscare_lunge_seconds.hint": "최종 확대까지 걸리는 시간",
		"ui.debug.jumpscare_lab.field.jumpscare_lunge_zoom.label": "돌진 확대",
		"ui.debug.jumpscare_lab.field.jumpscare_lunge_zoom.hint": "돌진이 끝났을 때의 크기",
		"ui.debug.jumpscare_lab.field.jumpscare_duration.label": "전체 길이",
		"ui.debug.jumpscare_lab.field.jumpscare_duration.hint": "첫 등장부터 종료까지",
		"ui.debug.jumpscare_lab.field.jumpscare_focus_x.label": "확대 중심 X",
		"ui.debug.jumpscare_lab.field.jumpscare_focus_x.hint": "0은 왼쪽, 1은 오른쪽",
		"ui.debug.jumpscare_lab.field.jumpscare_focus_y.label": "확대 중심 Y",
		"ui.debug.jumpscare_lab.field.jumpscare_focus_y.hint": "0은 위, 1은 아래",
		"ui.debug.jumpscare_lab.field.jumpscare_initial_shake.label": "첫 충격 진동",
		"ui.debug.jumpscare_lab.field.jumpscare_initial_shake.hint": "첫 프레임의 화면 진동",
		"ui.debug.jumpscare_lab.field.jumpscare_lunge_shake.label": "돌진 진동",
		"ui.debug.jumpscare_lab.field.jumpscare_lunge_shake.hint": "돌진 순간의 화면 진동",
		"ui.debug.jumpscare_lab.field.jumpscare_audio_volume_db.label": "충격음 음량",
		"ui.debug.jumpscare_lab.field.jumpscare_audio_volume_db.hint": "프리뷰 음량",
		"ui.debug.anomaly_transition.preview": "소멸 전환 테스트",
		"ui.debug.anomaly_transition.preview_tooltip": "게임 상태를 바꾸지 않고 기현상 소멸 전환만 재생합니다.",
		"ui.debug.anomaly_transition.duration": "기현상 페이드 시간",
		"ui.debug.anomaly_transition.value": "암전 %.2f초 / 전체 %.2f초",
		"ui.menu.brightness": "밝기",
		"ui.menu.main_menu": "메인 메뉴",
		"ui.menu.quit": "종료",
		"ui.shift.end": "근무 종료",
		"ui.day.label": "Day %d",
		"ui.infinity.day.label": "%d번째 무한 근무",
		"ui.lobby.title": "야간 근무",
		"ui.lobby.subtitle": "프론트 데스크가 기다리고 있습니다.",
		"ui.lobby.start_shift": "근무 시작",
		"ui.lobby.mode.story": "스토리",
		"ui.lobby.mode.infinity": "Infinity",
		"ui.lobby.mode.story.description": "정해진 이상현상 순서로 진행되는 7일간의 이야기입니다.",
		"ui.lobby.mode.infinity.description": "스토리 순서 없이 재사용 가능한 이상현상이 무작위로 등장하는 무한 근무입니다.",
		"ui.lobby.start_story": "스토리 시작",
		"ui.lobby.start_infinity": "Infinity 시작",
		"ui.lobby.continue_story": "스토리 계속하기",
		"ui.lobby.continue_infinity": "Infinity 계속하기",
		"ui.lobby.choose_infinity_night": "저장된 근무 선택",
		"ui.intro.dialogue.1": "새벽 12시 47분, 처음 보는 번호로 전화가 왔다.\n“미지급 급여가 남아 있습니다. 직접 오셔서 찾아가십시오.”",
		"ui.intro.dialogue.2": "나는 이 호텔에서 일한 적이 없다.\n그런데 직원 기록에는 내 이름과 두 개의 연락처가 있었다.",
		"ui.intro.dialogue.3": "두 번째 번호는 내 번호였다.",
		"ui.intro.dialogue.4": "도박 빚과 불법적인 일 때문에 숨어 지낸 지 오래였다.\n내 이름으로 남은 돈이라면 외면하기 어려웠다.",
		"ui.intro.dialogue.5": "직원 사진 속 사람은 실종된 친언니였다.\n언니는 이곳의 실종·납치 소문을 조사하며 내 이름으로 근무했다.",
		"ui.intro.dialogue.6": "기록 뒤편에는 언니 글씨로 한 줄이 남아 있었다.\n“동생을 찾으러 왔다고 말하지 마.”",
		"ui.intro.dialogue.7": "동생은 나인데.",
		"story.day.1.line.1": "새벽 12시 47분, 처음 보는 번호로 전화가 왔다.\n“미지급 급여가 남아 있습니다. 직접 오셔서 찾아가십시오.”",
		"story.day.1.line.2": "나는 이 호텔에서 일한 적이 없다. 하지만 도박 빚과 불법적인 일을 피해 몇 달째 숨어 지내던 내게, 내 이름으로 남은 돈은 외면하기 어려웠다.",
		"story.day.2.line.1": "내 이름으로 작성된 이전 직원 기록이 있었다. 그 아래에는 연락처 두 개가 적혀 있었다.",
		"story.day.3.line.1": "두 번째 연락처는 내 번호였다. 잠적한 뒤 바꾼, 지금 쓰는 번호였다.",
		"story.day.4.line.1": "기록에 붙은 사진은 실종된 친언니였다. 언니는 내 이름으로 이곳에서 일했다.",
		"story.day.5.line.1": "언니의 기록 가장자리에는 날짜와 객실 번호가 빼곡했다. 언니는 이 호텔에서 사람들이 사라진다는 소문을 추적하고 있었다.",
		"story.day.6.line.1": "기록 뒷면에는 언니 글씨로 한 문장만 남아 있었다.\n“동생을 찾으러 왔다고 말하지 마.”",
		"story.day.7.line.1": "언니는 여동생을 찾으러 이곳에 왔다.\n그 동생은 나다.",
		"night.phone.room_108_repair_call": "108호입니다. 전등이 나갔습니다. 수리하러 오세요. 통화가 끊겼다.",
		"night.child.hold_f_to_sing": "F를 길게 눌러 노래를 부르세요.",
		"ui.lobby.continue": "계속하기",
		"ui.lobby.continue.available": "저장된 day를 골라 이어서 시작합니다.",
		"ui.lobby.continue.disabled": "아직 저장된 day가 없습니다.",
		"ui.lobby.choose_day": "Day 선택",
		"ui.lobby.save_status": "최근 저장: %s",
		"ui.lobby.no_save_status": "저장된 근무가 없습니다.",
		"ui.lobby.day.saved": "이 저장 day에서 시작합니다.",
		"ui.lobby.day.locked": "먼저 이 day에 도달해야 합니다.",
		"ui.lobby.horror_summary": "%s",
		"ui.lobby.horror_summary.none": "발견한 이상현상: 0",
		"ui.lobby.horror_summary.count": "발견한 이상현상: %d (%s)",
		"ui.anomaly_collection.kind.visual_anomaly": "시각 이상",
		"ui.anomaly_collection.kind.jumpscare": "점프스케어",
		"ui.lobby.anomaly_collection": "이상현상 모음",
		"ui.lobby.quit": "종료",
		"ui.anomaly_collection.title": "이상현상 모음",
		"ui.anomaly_collection.count": "발견: %d · 엔티티: %d · 기현상: %d",
		"ui.anomaly_collection.empty": "아직 발견한 이상현상이 없습니다.",
		"ui.anomaly_collection.kind.entity": "엔티티",
		"ui.anomaly_collection.kind.phenomenon": "기현상",
		"ui.anomaly_collection.body.story": "스토리",
		"ui.anomaly_collection.body.description": "현상 설명",
		"ui.anomaly_collection.type.anomaly": "이상현상",
		"ui.anomaly_collection.type.jumpscare": "점프스케어",
		"ui.anomaly_collection.status.active": "발견됨",
		"ui.anomaly_collection.status.resolved": "해결됨",
		"ui.inventory.title": "인벤토리",
		"ui.inventory.hint": "드래그하거나 왼쪽 더블클릭 또는 오른쪽 클릭으로 장착합니다. 아이템끼리 겹치면 조합합니다.",
		"ui.inventory.empty": "아직 아이템이 없습니다.",
		"ui.inventory.combine.no_match": "이 아이템들은 서로 맞지 않습니다.",
		"ui.inventory.hand.title": "Hand",
		"ui.inventory.hand.empty": "장착된 아이템 없음",
		"ui.inventory.hand.empty_hint": "아이템을 놓거나 선택하세요",
		"ui.inventory.hand.status.empty": "○ 비어 있음",
		"ui.inventory.hand.status.equipped": "● 장착 중",
		"ui.inventory.hand.use_hint": "F를 눌러 사용",
		"ui.equipment.empty": "비어 있음",
		"ui.equipment.tooltip": "인벤토리 열기",
		"ui.rule_book.title": "호텔 관리 규칙",
		"ui.rule_book.subtitle": "발행: 관리자",
		"ui.rule_book.day": "DAY %d · 새로 추가된 규칙",
		"ui.rule_book.latest": "최신",
		"ui.rule_book.previous_day": "이전 Day",
		"ui.rule_book.next_day": "다음 Day",
		"ui.rule_book.rule.1": "비어 있는 모든 객실의 이불을 정리하십시오.",
		"ui.rule_book.rule.2": "객실에서 나온 쓰레기는 반드시 객실 쓰레기통에 넣으십시오.",
		"ui.rule_book.rule.3": "사용한 이불은 이틀에 한 번 빨래통에 넣으십시오.",
		"ui.rule_book.rule.4": "객실 옷장 문이 열려 있으면 닫으시오.",
		"ui.rule_book.rule.5": "108호에서 전등 수리 요청 전화가 걸려 올 경우, 요청을 무시하시오. 객실에 들어가지 마시오.",
		"ui.rule_book.rule.6": "세 번째 날부터 109호 문이 열려 있는 경우 들여다보지 마시오.",
		"ui.rule_book.rule.7": "프런트 전화는 13번째 벨이 울리기 전에 받으시오.",
		"ui.rule_book.rule.8": "세탁기 안에 이상한 것이 보이면 세탁을 종료하시오. 세탁 종료 노래가 나오는 동안 눈을 감고, 세탁실에 숨어 있으시오",
		"ui.rule_book.rule.12": "우는 아이를 발견하면 눈을 감고 노래를 부르시오.",
		"ui.rule_book.rule.14": "오늘 밤에는 109호 문을 열어 두시오.",
		"ui.rule_book.rule.15": "109호에서 나오는 사람을 막지 마시오.",
		"ui.rule_book.rule.16": "발소리가 멎기 전까지 뒤돌아보지 마시오.",
		"ui.rule_book.rule.17": "귀여운 여자아이에겐 인형을 주시오.",
		"ui.rule_book.rule.18": "누군가 따라온다면 벨을 여러 번 빠르게 울리고 도망치십시오.",
		"ui.debug.days.title": "Day",
		"ui.debug.days.tooltip": "현재 day를 자동 저장하고 이 day로 이동합니다.",
		"ui.debug.hotspots.show": "클릭 영역 표시",
		"ui.debug.hotspots.hide": "클릭 영역 숨기기",
		"ui.debug.dialogue.show": "대화 패널 표시",
		"ui.debug.dialogue.hide": "대화 패널 숨기기",
		"ui.debug.navigation.show": "빠른 이동 버튼 표시",
		"ui.debug.navigation.hide": "빠른 이동 버튼 숨기기",
		"item.room_105_key.name": "105호 열쇠",
		"item.room_105_key.description": "프론트 서랍에서 나온 낡은 황동 열쇠입니다.",
		"item.small_flashlight.name": "손전등",
		"item.small_flashlight.description": "작은 손전등입니다. 전기가 나가면 쓸모가 있습니다.",
		"item.guest_note.name": "손님 메모",
		"item.guest_note.description": "연필로 방 번호가 적힌 접힌 메모입니다.",
		"item.revealed_guest_note.name": "드러난 메모",
		"item.revealed_guest_note.description": "손전등을 비추자 방 번호 아래 희미한 문장이 보입니다. 자정 이후에는 돌려주지 말 것.",
		"item.cleaning_cloth.name": "청소용 천",
		"item.cleaning_cloth.description": "세면대, 바닥, 직접 만지기 싫은 것을 닦는 거친 천입니다.",
		"item.small_mirror.name": "작은 거울",
		"item.small_mirror.description": "손에 들어오는 작은 거울입니다. 표면이 이상할 정도로 선명합니다.",
		"item.hell_mirror.name": "지옥의 거울",
		"item.hell_mirror.description": "들고 있는 동안 갇힌 절규가 커진다. 세탁기 드럼이라면 이 거울을 부술 수 있을지도 모른다.",
		"horror.room_106_horrific_mirror.transferred": "작은 거울로 끔찍한 형상이 옮겨졌다. 들고 있으면 영혼의 절규가 들려온다.",
		"item.cute_doll.name": "귀여운 인형",
		"item.cute_doll.description": "세탁실 탁자에서 발견한 작은 목각 인형입니다. 손에 들 수 있으며, 건넬 때는 인벤토리에 있기만 하면 됩니다.",
		"item.collected_trash.name": "수거한 쓰레기",
		"item.collected_trash.description": "객실 업무 중 모은 종이와 쓰레기입니다.",
		"combine.reveal_guest_note": "손전등 불빛 아래 메모의 숨은 글씨가 드러났습니다.",
		"task.room_105_fold_bedding.label": "이불",
		"task.room_105_fold_bedding.text": "침대가 아직 손님을 받을 상태는 아닙니다.",
		"task.room_105_fold_bedding.done": "이불을 네모나게 각 잡아 정리했습니다.",
		"task.room_105_clean_sink.label": "세면대 얼룩",
		"task.room_105_clean_sink.text": "세면대에 닦아야 할 흐릿한 얼룩이 있습니다.",
		"task.room_105_clean_sink.done": "다음 손님이 써도 될 만큼 세면대가 깨끗해졌습니다.",
		"task.room_105_clean_sink.blocked": "세면대를 닦을 만한 물건이 필요합니다.",
		"task.room_107_collect_papers.label": "흩어진 종이",
		"task.room_107_collect_papers.text": "카펫 위에 종이 몇 장이 흩어져 있습니다.",
		"task.room_107_collect_papers.done": "카펫 위의 종이를 주워 모았습니다.",
		"hotspot.laundry_room.laundry_second_washer.opened": "두 번째 세탁기 문이 열렸습니다.",
		"hotspot.laundry_room.laundry_second_washer.closed": "두 번째 세탁기 문이 닫혔습니다.",
		"horror.room.front_desk": "프론트",
		"horror.room.corridor": "복도",
		"horror.room.laundry_room": "세탁실",
		"horror.room.exterior_stairs": "외부 계단",
		"horror.room.room_105": "105호",
		"horror.room.room_106": "106호",
		"horror.room.room_107": "107호",
		"horror.room.room_108": "108호",
		"horror.room.room_109": "109호",
		"hotspot.room_105_bathroom_entry.closet_pig_hold:wardrobe.label": "옷장 닫기",
		"hotspot.room_105_bathroom_entry.closet_pig_hold:wardrobe.text": "계속 눌러 남자를 밀어 넣고 옷장 문을 닫습니다.",
		"horror_event.room_105_closet_pig_man.title": "옷장의 돼지 가면 남자",
		"horror_event.room_105_closet_pig_man.description": "창백한 돼지 가면을 쓴 남자가 열린 옷장을 밀고 나옵니다.",
		"horror_event.room_106_abandoned_child.title": "등록되지 않은 아이",
		"horror_event.room_106_abandoned_child.description": "아이의 울음이 바로 뒤에서 멎습니다.",
		"horror_event.room_108_light_repair_call.title": "열세 번째 전화벨",
		"horror_event.room_108_light_repair_call.description": "108호에서 다시 전화가 옵니다. 이번에는 목소리가 바로 옆에서 들립니다.",
		"horror_event.room_109_open_door.title": "109호",
		"horror_event.room_109_open_door.description": "안쪽의 무언가가 당신이 들여다본 것을 알아챕니다.",
		"horror_event.room_109_day7_passage.title": "109호 통과",
		"horror_event.room_109_day7_passage.description": "뒤에서 이어지던 발소리가 멎기 전에 돌아보았습니다.",
		"horror_event.laundry_red_washer.title": "붉은 빨래",
		"horror_event.laundry_red_washer.description": "들여다보는 순간 젖은 빨랫감이 움직입니다.",
		"horror_event.room_107_hanging_girl.title": "목을 맨 목각 여자 인형",
		"horror_event.room_107_hanging_girl.description": "몸이 죽어야 할 때가 지나도 데롱데롱 놀이는 끝나지 않았습니다.",
		"horror_event.vacant_room_blanket_child.title": "이불 속 아이",
		"horror_event.vacant_room_blanket_child.description": "이불 아래의 목소리가 당신을 찾았다고 속삭입니다.",
		"horror_event.hotel_following_shadow.title": "따라오는 그림자",
		"horror_event.hotel_following_shadow.description": "모든 발소리를 따라 하던 존재가 마침내 바로 뒤까지 따라붙습니다.",
		"horror_event.hell_mirror.title": "지옥의 거울",
		"horror_event.hell_mirror.description": "거울 안에 갇힌 절규가 마침내 반대편까지 닿습니다.",
		"horror.hanging_girl.prompt.interact": "목을 맨 목각 여자 인형이 이쪽을 보고 있다.",
		"horror.hanging_girl.prompt.play": "데롱데롱 놀이야~ 재밌겠지?",
		"horror.hanging_girl.prompt.angry": "이 씨발새끼야.",
		"horror.hanging_girl.prompt.which_game": "어떤 놀인데?",
		"horror.hanging_girl.prompt.who_walter": "윌터가 누구야?",
		"horror.hanging_girl.choice.talk": "대화한다",
		"horror.hanging_girl.choice.ignore": "무시한다",
		"horror.hanging_girl.choice.fun_yes": "재미있어 보여",
		"horror.hanging_girl.choice.fun_no": "재미없어 보여",
		"horror.hanging_girl.choice.changed_mind": "다시 보니 재미있어 보여",
		"horror.hanging_girl.choice.you_play": "너나 많이 해",
		"horror.hanging_girl.choice.better_game": "더 재밌는 놀이를 알려줄게",
		"horror.hanging_girl.choice.doll_play": "인형 놀이",
		"horror.hanging_girl.choice.hide_and_seek": "숨바꼭질 놀이",
		"horror.hanging_girl.choice.your_mom": "니 엄마다",
		"horror.hanging_girl.choice.walter": "윌터는 재미있어 보인대",
		"horror.hanging_girl.choice.doll_friend": "내 인형 친구야",
		"horror.hanging_girl.death.1": "밧줄이 목을 조였다.",
		"horror.hanging_girl.death.2": "죽지 못한 채 몸이 오래 흔들렸다.",
		"horror.hanging_girl.death.3": "혀가 입 밖으로 밀려 나왔다.",
		"horror.hanging_girl.death.4": "토사물이 턱과 가슴을 타고 흘렀다.",
		"horror.hanging_girl.death.5": "괄약근이 풀리며 장에 남은 것이 전부 쏟아졌다.",
		"horror.hanging_girl.death.6": "발버둥은 한참 뒤에야 멎었다.",
	},
	Language.JAPANESE: {
		"ui.menu.title": "メニュー",
		"ui.menu.continue": "続ける",
		"ui.menu.inventory": "インベントリ",
		"ui.menu.rule_book": "ルールブック",
		"ui.menu.brightness": "明るさ",
		"ui.menu.main_menu": "メインメニュー",
		"ui.menu.quit": "終了",
		"ui.day.label": "Day %d",
		"ui.lobby.title": "夜勤",
		"ui.lobby.subtitle": "フロントデスクが待っています。",
		"ui.lobby.start_shift": "勤務開始",
		"ui.lobby.continue": "続ける",
		"ui.lobby.continue.available": "保存済みの日を選んで再開します。",
		"ui.lobby.continue.disabled": "保存済みの日はまだありません。",
		"ui.lobby.choose_day": "Day 選択",
		"ui.lobby.save_status": "最新の保存: %s",
		"ui.lobby.no_save_status": "保存された勤務はありません。",
		"ui.lobby.day.saved": "この保存日から始めます。",
		"ui.lobby.day.locked": "先にこの日に到達してください。",
		"ui.lobby.horror_summary": "%s",
		"ui.lobby.horror_summary.none": "発見した異常: 0",
		"ui.lobby.horror_summary.count": "発見した異常: %d（%s）",
		"ui.anomaly_collection.kind.visual_anomaly": "視覚異常",
		"ui.anomaly_collection.kind.jumpscare": "ジャンプスケア",
		"ui.lobby.anomaly_collection": "異常一覧",
		"ui.lobby.quit": "終了",
		"ui.anomaly_collection.title": "異常一覧",
		"ui.anomaly_collection.count": "発見: %d・エンティティ: %d・現象: %d",
		"ui.anomaly_collection.empty": "発見した異常はまだありません。",
		"ui.anomaly_collection.kind.entity": "エンティティ",
		"ui.anomaly_collection.kind.phenomenon": "現象",
		"ui.anomaly_collection.body.story": "ストーリー",
		"ui.anomaly_collection.body.description": "現象の説明",
		"ui.anomaly_collection.type.anomaly": "異常",
		"ui.anomaly_collection.type.jumpscare": "ジャンプスケア",
		"ui.anomaly_collection.status.active": "発見済み",
		"ui.anomaly_collection.status.resolved": "解決済み",
		"ui.inventory.title": "インベントリ",
		"ui.inventory.hint": "ドラッグ、左ダブルクリック、右クリックで装備できます。アイテム同士を重ねると組み合わせられます。",
		"ui.inventory.empty": "アイテムはまだありません。",
		"ui.inventory.combine.no_match": "そのアイテム同士は合いません。",
		"ui.inventory.hand.title": "Hand",
		"ui.inventory.hand.empty": "装備なし",
		"ui.inventory.hand.empty_hint": "アイテムを置くか選択",
		"ui.inventory.hand.status.empty": "○ 空き",
		"ui.inventory.hand.status.equipped": "● 装備中",
		"ui.inventory.hand.use_hint": "Fで使用",
		"ui.equipment.empty": "なし",
		"ui.equipment.tooltip": "インベントリを開く",
		"ui.rule_book.title": "ホテル管理規則",
		"ui.rule_book.subtitle": "発行者：管理人",
		"ui.rule_book.rule.1": "空室のベッドをすべて整えてください。",
		"ui.rule_book.rule.2": "客室のごみは必ず客室のごみ箱に入れてください。",
		"ui.rule_book.rule.3": "使用済みの寝具は二日に一度ランドリーバスケットへ入れてください。",
		"ui.rule_book.rule.4": "客室のクローゼットの扉が開いていたら、閉めてください。",
		"ui.rule_book.rule.5": "108号室から照明修理の電話が来た場合、依頼を無視し、入室しないでください。",
		"ui.rule_book.rule.6": "三日目以降、109号室の扉が開いていても中を覗かないでください。",
		"ui.rule_book.rule.7": "フロントの電話は13回目のベルが鳴る前に取ってください。",
		"ui.rule_book.rule.8": "洗濯機の中に異様なものが見えたら、洗濯を終了してください。洗濯終了のメロディーが流れている間は目を閉じ、ランドリールームに隠れていてください。",
		"ui.rule_book.rule.12": "泣いている子供を見つけたら、目を閉じて歌ってください。",
		"ui.rule_book.rule.14": "今夜は109号室の扉を開けておいてください。",
		"ui.rule_book.rule.15": "109号室から出てくる者を止めないでください。",
		"ui.rule_book.rule.16": "足音が止むまで振り返らないでください。",
		"ui.rule_book.rule.18": "誰かにつけられているなら、ベルを素早く何度も鳴らして逃げてください。",
		"ui.debug.days.title": "Day",
		"ui.debug.days.tooltip": "現在の日を自動保存して、この日に移動します。",
		"item.room_105_key.name": "105号室の鍵",
		"item.room_105_key.description": "フロントの引き出しにあった古い真鍮の鍵です。",
		"item.small_flashlight.name": "懐中電灯",
		"item.small_flashlight.description": "小型の懐中電灯です。停電時に役立ちます。",
		"item.guest_note.name": "客のメモ",
		"item.guest_note.description": "鉛筆で部屋番号が書かれた折りたたみメモです。",
		"item.revealed_guest_note.name": "浮かび上がったメモ",
		"item.revealed_guest_note.description": "懐中電灯を当てると、部屋番号の下に薄い文字が見えます。深夜以降は返してはいけない。",
		"item.cleaning_cloth.name": "掃除用クロス",
		"item.cleaning_cloth.description": "洗面台や床、直接触れたくないものを拭くための粗い布です。",
		"item.collected_trash.name": "回収したゴミ",
		"item.collected_trash.description": "客室作業中に集めた紙とゴミです。",
		"combine.reveal_guest_note": "懐中電灯の光でメモの隠れた文字が浮かび上がりました。",
		"task.room_105_fold_bedding.label": "寝具",
		"task.room_105_fold_bedding.text": "ベッドはまだ客を入れられる状態ではありません。",
		"task.room_105_fold_bedding.done": "寝具を四角くきちんと整えました。",
		"task.room_105_clean_sink.label": "洗面台の染み",
		"task.room_105_clean_sink.text": "洗面台に拭き取るべきくすんだ染みがあります。",
		"task.room_105_clean_sink.done": "洗面台は次の客に出せる程度にはきれいになりました。",
		"task.room_105_clean_sink.blocked": "洗面台を拭くものが必要です。",
		"task.room_107_collect_papers.label": "散らばった紙",
		"task.room_107_collect_papers.text": "カーペットに紙が数枚散らばっています。",
		"task.room_107_collect_papers.done": "カーペットの紙を回収しました。",
		"horror.room.front_desk": "フロント",
		"horror.room.corridor": "廊下",
		"horror.room.laundry_room": "ランドリールーム",
		"horror.room.exterior_stairs": "外階段",
		"horror.room.room_105": "105号室",
		"horror.room.room_106": "106号室",
		"horror.room.room_107": "107号室",
		"horror.room.room_108": "108号室",
		"horror.room.room_109": "109号室",
	},
	Language.RUSSIAN: {
		"ui.menu.title": "Меню",
		"ui.menu.continue": "Продолжить",
		"ui.menu.inventory": "Инвентарь",
		"ui.menu.rule_book": "Книга правил",
		"ui.menu.brightness": "Яркость",
		"ui.menu.main_menu": "Главное меню",
		"ui.menu.quit": "Выйти",
		"ui.day.label": "Day %d",
		"ui.lobby.title": "Ночная смена",
		"ui.lobby.subtitle": "Стойка регистрации ждет.",
		"ui.lobby.start_shift": "Начать смену",
		"ui.lobby.continue": "Продолжить",
		"ui.lobby.continue.available": "Выберите сохраненный день для продолжения.",
		"ui.lobby.continue.disabled": "Сохраненных дней пока нет.",
		"ui.lobby.choose_day": "Выбрать Day",
		"ui.lobby.save_status": "Последнее сохранение: %s",
		"ui.lobby.no_save_status": "Сохраненной смены пока нет.",
		"ui.lobby.day.saved": "Начать с этого сохраненного дня.",
		"ui.lobby.day.locked": "Сначала дойдите до этого дня.",
		"ui.lobby.horror_summary": "%s",
		"ui.lobby.horror_summary.none": "Найдено аномалий: 0",
		"ui.lobby.horror_summary.count": "Найдено аномалий: %d (%s)",
		"ui.anomaly_collection.kind.visual_anomaly": "Визуальные",
		"ui.anomaly_collection.kind.jumpscare": "Скримеры",
		"ui.lobby.anomaly_collection": "Коллекция аномалий",
		"ui.lobby.quit": "Выйти",
		"ui.anomaly_collection.title": "Коллекция аномалий",
		"ui.anomaly_collection.count": "Обнаружено: %d · Сущности: %d · Явления: %d",
		"ui.anomaly_collection.empty": "Обнаруженных аномалий пока нет.",
		"ui.anomaly_collection.kind.entity": "Сущность",
		"ui.anomaly_collection.kind.phenomenon": "Явление",
		"ui.anomaly_collection.body.story": "ИСТОРИЯ",
		"ui.anomaly_collection.body.description": "ОПИСАНИЕ ЯВЛЕНИЯ",
		"ui.anomaly_collection.type.anomaly": "Аномалия",
		"ui.anomaly_collection.type.jumpscare": "Скример",
		"ui.anomaly_collection.status.active": "Обнаружено",
		"ui.anomaly_collection.status.resolved": "Устранена",
		"ui.inventory.title": "Инвентарь",
		"ui.inventory.hint": "Экипируйте перетаскиванием, двойным левым или правым щелчком. Наложите предметы для объединения.",
		"ui.inventory.empty": "Предметов пока нет.",
		"ui.inventory.combine.no_match": "Эти предметы не подходят друг к другу.",
		"ui.inventory.hand.title": "Hand",
		"ui.inventory.hand.empty": "Ничего не экипировано",
		"ui.inventory.hand.empty_hint": "Перетащите или выберите предмет",
		"ui.inventory.hand.status.empty": "○ ПУСТО",
		"ui.inventory.hand.status.equipped": "● ЭКИПИРОВАНО",
		"ui.inventory.hand.use_hint": "Нажмите F для использования",
		"ui.equipment.empty": "Пусто",
		"ui.equipment.tooltip": "Открыть инвентарь",
		"ui.rule_book.title": "Правила управления отелем",
		"ui.rule_book.subtitle": "Издано: управляющий",
		"ui.rule_book.rule.1": "Заправьте кровати во всех свободных номерах.",
		"ui.rule_book.rule.2": "Весь мусор из номера кладите в его мусорную корзину.",
		"ui.rule_book.rule.3": "Раз в два дня относите использованное белье в корзину прачечной.",
		"ui.rule_book.rule.4": "Если дверь шкафа в гостевом номере открыта, закройте её.",
		"ui.rule_book.rule.5": "Если из номера 108 просят починить свет, игнорируйте просьбу и не входите.",
		"ui.rule_book.rule.6": "Начиная с третьего дня не заглядывайте в открытую дверь номера 109.",
		"ui.rule_book.rule.7": "Ответьте на телефон стойки до тринадцатого звонка.",
		"ui.rule_book.rule.8": "Если внутри стиральной машины видно что-то странное, остановите стирку. Пока играет мелодия завершения, закройте глаза и спрячьтесь в прачечной.",
		"ui.rule_book.rule.12": "Увидев плачущего ребенка, закройте глаза и пойте.",
		"ui.rule_book.rule.14": "Сегодня оставьте дверь номера 109 открытой.",
		"ui.rule_book.rule.15": "Не останавливайте того, кто выйдет из номера 109.",
		"ui.rule_book.rule.16": "Не оборачивайтесь, пока шаги не стихнут.",
		"ui.rule_book.rule.18": "Если за вами кто-то следует, быстро позвоните в звонок несколько раз и бегите.",
		"ui.debug.days.title": "Day",
		"ui.debug.days.tooltip": "Автосохранить текущий день и перейти к этому дню.",
		"item.room_105_key.name": "Ключ от номера 105",
		"item.room_105_key.description": "Потертый латунный ключ из ящика стойки регистрации.",
		"item.small_flashlight.name": "Фонарик",
		"item.small_flashlight.description": "Компактный фонарик. Пригодится, если отключится электричество.",
		"item.guest_note.name": "Записка гостя",
		"item.guest_note.description": "Сложенная записка с номером комнаты, написанным карандашом.",
		"item.revealed_guest_note.name": "Проявленная записка",
		"item.revealed_guest_note.description": "В свете фонарика под номером комнаты видна бледная надпись: не возвращать после полуночи.",
		"item.cleaning_cloth.name": "Тряпка для уборки",
		"item.cleaning_cloth.description": "Грубая тряпка для раковин, полов и вещей, которых лучше не касаться руками.",
		"item.collected_trash.name": "Собранный мусор",
		"item.collected_trash.description": "Бумаги и мусор, собранные во время работы в номере.",
		"combine.reveal_guest_note": "Свет фонарика проявляет скрытую надпись на записке.",
		"task.room_105_fold_bedding.label": "Постель",
		"task.room_105_fold_bedding.text": "Кровать еще не готова для гостя.",
		"task.room_105_fold_bedding.done": "Вы складываете постель в аккуратный жесткий квадрат.",
		"task.room_105_clean_sink.label": "Пятно у раковины",
		"task.room_105_clean_sink.text": "На раковине есть тусклое пятно, которое нужно протереть.",
		"task.room_105_clean_sink.done": "Раковина выглядит достаточно чистой для следующего гостя.",
		"task.room_105_clean_sink.blocked": "Нужно чем-то протереть раковину.",
		"task.room_107_collect_papers.label": "Разбросанные бумаги",
		"task.room_107_collect_papers.text": "На ковре разбросано несколько листов.",
		"task.room_107_collect_papers.done": "Вы собираете бумаги с ковра.",
		"horror.room.front_desk": "Стойка регистрации",
		"horror.room.corridor": "Коридор",
		"horror.room.laundry_room": "Прачечная",
		"horror.room.exterior_stairs": "Наружная лестница",
		"horror.room.room_105": "Номер 105",
		"horror.room.room_106": "Номер 106",
		"horror.room.room_107": "Номер 107",
		"horror.room.room_108": "Номер 108",
		"horror.room.room_109": "Номер 109",
	},
	Language.CHINESE: {
		"ui.menu.title": "菜单",
		"ui.menu.continue": "继续",
		"ui.menu.inventory": "物品栏",
		"ui.menu.rule_book": "规则书",
		"ui.menu.brightness": "亮度",
		"ui.menu.main_menu": "主菜单",
		"ui.menu.quit": "退出",
		"ui.day.label": "Day %d",
		"ui.lobby.title": "夜班",
		"ui.lobby.subtitle": "前台正在等待。",
		"ui.lobby.start_shift": "开始值班",
		"ui.lobby.continue": "继续",
		"ui.lobby.continue.available": "选择已保存的日期继续。",
		"ui.lobby.continue.disabled": "还没有已保存的日期。",
		"ui.lobby.choose_day": "选择 Day",
		"ui.lobby.save_status": "最近保存：%s",
		"ui.lobby.no_save_status": "还没有保存的值班。",
		"ui.lobby.day.saved": "从这个已保存日期开始。",
		"ui.lobby.day.locked": "请先到达这个日期。",
		"ui.lobby.horror_summary": "%s",
		"ui.lobby.horror_summary.none": "已发现异常：0",
		"ui.lobby.horror_summary.count": "已发现异常：%d（%s）",
		"ui.anomaly_collection.kind.visual_anomaly": "视觉异常",
		"ui.anomaly_collection.kind.jumpscare": "惊吓",
		"ui.lobby.anomaly_collection": "异常收集",
		"ui.lobby.quit": "退出",
		"ui.anomaly_collection.title": "异常收集",
		"ui.anomaly_collection.count": "已发现：%d · 实体：%d · 奇异现象：%d",
		"ui.anomaly_collection.empty": "还没有发现异常。",
		"ui.anomaly_collection.kind.entity": "实体",
		"ui.anomaly_collection.kind.phenomenon": "奇异现象",
		"ui.anomaly_collection.body.story": "故事",
		"ui.anomaly_collection.body.description": "现象说明",
		"ui.anomaly_collection.type.anomaly": "异常",
		"ui.anomaly_collection.type.jumpscare": "惊吓",
		"ui.anomaly_collection.status.active": "已发现",
		"ui.anomaly_collection.status.resolved": "已解决",
		"ui.inventory.title": "物品栏",
		"ui.inventory.hint": "拖拽、左键双击或右键单击均可装备。将物品叠放可尝试组合。",
		"ui.inventory.empty": "还没有物品。",
		"ui.inventory.combine.no_match": "这些物品无法组合。",
		"ui.inventory.hand.title": "Hand",
		"ui.inventory.hand.empty": "未装备物品",
		"ui.inventory.hand.empty_hint": "拖入或选择物品",
		"ui.inventory.hand.status.empty": "○ 空",
		"ui.inventory.hand.status.equipped": "● 已装备",
		"ui.inventory.hand.use_hint": "按 F 使用",
		"ui.equipment.empty": "空",
		"ui.equipment.tooltip": "打开物品栏",
		"ui.rule_book.title": "酒店管理规则",
		"ui.rule_book.subtitle": "发布者：管理员",
		"ui.rule_book.rule.1": "整理所有空房的床铺。",
		"ui.rule_book.rule.2": "客房内的垃圾必须放入该房间的垃圾桶。",
		"ui.rule_book.rule.3": "每两天将用过的床品放入洗衣篮。",
		"ui.rule_book.rule.4": "若客房衣柜门开着，请将其关上。",
		"ui.rule_book.rule.5": "若108号房来电要求维修电灯，忽略请求且不要进入该房间。",
		"ui.rule_book.rule.6": "从第三天起，若109号房门开着，不要向内窥视。",
		"ui.rule_book.rule.7": "前台电话必须在第十三次铃响前接听。",
		"ui.rule_book.rule.8": "如果洗衣机里出现异常物体，请停止洗涤。洗衣结束音乐播放期间，闭上眼睛并藏在洗衣房里。",
		"ui.rule_book.rule.12": "发现哭泣的孩子时，请闭上眼睛唱歌。",
		"ui.rule_book.rule.14": "今晚让109号房门保持开启。",
		"ui.rule_book.rule.15": "不要阻拦从109号房出来的人。",
		"ui.rule_book.rule.16": "脚步声停止前不要回头。",
		"ui.rule_book.rule.18": "若有人跟着你，快速连续按响前台铃数次，然后逃跑。",
		"ui.debug.days.title": "Day",
		"ui.debug.days.tooltip": "自动保存当前日期并跳转到此日期。",
		"item.room_105_key.name": "105号房钥匙",
		"item.room_105_key.description": "前台抽屉里的一把旧黄铜钥匙。",
		"item.small_flashlight.name": "手电筒",
		"item.small_flashlight.description": "一支小手电。停电时会派上用场。",
		"item.guest_note.name": "客人便条",
		"item.guest_note.description": "一张折起来的便条，上面用铅笔写着房号。",
		"item.revealed_guest_note.name": "显现的便条",
		"item.revealed_guest_note.description": "手电光照出房号下方的淡字：午夜后不要归还。",
		"item.cleaning_cloth.name": "清洁布",
		"item.cleaning_cloth.description": "一块粗糙的布，用来擦洗手池、地板和不该直接触碰的东西。",
		"item.collected_trash.name": "收集的垃圾",
		"item.collected_trash.description": "客房工作中收集到的纸张和垃圾。",
		"combine.reveal_guest_note": "手电光让便条上的隐藏文字显现出来。",
		"task.room_105_fold_bedding.label": "床品",
		"task.room_105_fold_bedding.text": "这张床还没有准备好给客人使用。",
		"task.room_105_fold_bedding.done": "你把床品叠成整齐僵硬的方块。",
		"task.room_105_clean_sink.label": "洗手池污渍",
		"task.room_105_clean_sink.text": "洗手池上有一块暗淡的污渍需要擦掉。",
		"task.room_105_clean_sink.done": "洗手池看起来已经足够干净，可以给下一位客人使用。",
		"task.room_105_clean_sink.blocked": "你需要能擦洗手池的东西。",
		"task.room_107_collect_papers.label": "散落的纸",
		"task.room_107_collect_papers.text": "地毯上散落着几张纸。",
		"task.room_107_collect_papers.done": "你把地毯上的纸收集起来。",
		"horror.room.front_desk": "前台",
		"horror.room.corridor": "走廊",
		"horror.room.laundry_room": "洗衣房",
		"horror.room.exterior_stairs": "外部楼梯",
		"horror.room.room_105": "105号房",
		"horror.room.room_106": "106号房",
		"horror.room.room_107": "107号房",
		"horror.room.room_108": "108号房",
		"horror.room.room_109": "109号房",
	},
}


func _init() -> void:
	SceneLocalizationContent.append_translations(translations, Language.ENGLISH, Language.KOREAN)
	AnomalyCollectionContent.append_translations(translations, LANGUAGE_CODES)


func set_language(language: int) -> void:
	if not SUPPORTED_LANGUAGES.has(language) or current_language == language:
		return

	current_language = language
	language_changed.emit(current_language)


func get_language() -> int:
	return current_language


func get_language_code() -> String:
	return LANGUAGE_CODES.get(current_language, LANGUAGE_CODES[DEFAULT_LANGUAGE])


func get_supported_languages() -> Array:
	return SUPPORTED_LANGUAGES.duplicate()


func translate(key: String, fallback: String = "") -> String:
	var table: Dictionary = translations.get(current_language, {})
	if table.has(key):
		return table[key]

	var english_table: Dictionary = translations.get(FALLBACK_LANGUAGE, {})
	if english_table.has(key):
		return english_table[key]

	return fallback


func translate_ui(key: String, fallback: String = "") -> String:
	return translate("ui.%s" % key, fallback)


func translate_item_name(item_id: String, fallback: String = "") -> String:
	return translate("item.%s.name" % item_id, fallback)


func translate_item_description(item_id: String, fallback: String = "") -> String:
	return translate("item.%s.description" % item_id, fallback)


func translate_scene_photo(scene_id: String, fallback: String = "", variant := "") -> String:
	var key := "scene.%s.photo" % scene_id
	if not variant.is_empty():
		key = "%s.%s" % [key, variant]

	return translate(key, fallback)
